"""Stage 1c: source-passage English for a DK context run (docs/source-
passage-english-scoping.md — Phase C's mechanism sketch, phase 1 of the
phased plan: Diogenes Laertius). DRAFT pending John's approval of the
reader-facing credit copy (see shared/components/Reader.svelte's
`.context-english` block and the strings quoted there).

A DK fragment/testimonia work MAY declare `sources/<work>/context-english.json`
-- a hand-authored, per-work sidecar keyed by SEGMENT id (the spine's own
"<book>:<column>" token, e.g. "1:A1"), one entry per column carrying a
`context_spans` list. Each span names the SOURCE author/work a `role:
"context"` Greek run quotes from (or is quoted BY), keyed at the
carried-forward-source-run granularity the census established (docs/
source-passage-english-scoping.md, Phase A) -- not per raw context line.

This is a LOCUS POINTER, never a pasted duplicate: a `status: "translated"`
span names a `source_author` this module knows how to resolve (today, only
"Diogenes Laertius" -> the vendored Hicks Loeb store already used for the
`lives` work's own English -- see stage1_book_section_english.py and
sources/hicks-dl/hicks-lives.clean.json) plus a `locus` string resolved
against that store at BUILD TIME, so the emitted text can never drift from
the vendored Hicks JSON. A `status: "desert"` span carries no text at all --
an honest "no PD English exists for this passage" state the reader renders
as its own notice, not a silent fallback.

A work with no context-english.json file at all is completely unaffected --
`run` returns None and stage7_emit attaches no `contextEnglish` key to any
segment (byte-identical output to before this module existed).

## Fatal gates (this module IS the preflight for this sidecar; there is no
separate DIST-level cross-check yet -- see docs/source-passage-english-
scoping.md's implementation section for why that is a phase-2 item)

- The declaration file must not be empty -- `{}` is fatal (an honest "no
  sidecar" state is the file not existing at all; a present-but-empty file
  reads as a truncated write and must not silently pass as "no coverage
  declared").
- The declaration's top-level keys must all match a real spine segment id
  (`f"{book}:{column}"`) -- an unknown column is fatal.
- Every span must carry `source_author`, `source_work`, `locus`, `status`
  (status must be "translated" or "desert") -- a missing/bad field is fatal.
- A "translated" span must carry a non-empty `translation_credit` and its
  `(source_author, source_work)` PAIR must be one this module has a
  resolver registered for -- registered by the exact pair, not by author
  alone, so a declaration that names the right author but the wrong work
  (e.g. "Diogenes Laertius" + "Metaphysics") can never resolve against the
  wrong store. The `locus` must full-match that resolver's syntax and then
  resolve against its store (a locus naming a section the store doesn't
  carry is fatal -- never a silent partial/empty result).
- A "desert" span must NOT carry `translation_credit` (nothing to credit).
"""

from __future__ import annotations

import json
import re
from pathlib import Path

from .config import BUILD_DIR, SOURCES_DIR, Manifest


def _load_hicks() -> dict[str, str]:
    # SOURCES_DIR read at call time (not bound to a module-level constant at
    # import time) so tests can monkeypatch it, same posture as every other
    # stage1 module's SOURCES_DIR-relative lookups.
    path = SOURCES_DIR / "hicks-dl" / "hicks-lives.clean.json"
    return json.loads(path.read_text(encoding="utf-8"))


def _load_plato() -> dict[str, str]:
    # Same call-time SOURCES_DIR read as _load_hicks -- see that function's
    # comment. One flat store shared by all 18 vendored dialogues (docs/
    # plato-locus-resolver-design.md SS2.4), keyed "<slug>:<page><letter>".
    path = SOURCES_DIR / "perseus-plato" / "plato-stephanus.clean.json"
    return json.loads(path.read_text(encoding="utf-8"))


# Per-passage translation picker (REVIEW-CHECKLIST item 82): a second, ALT
# store of the same flat "<slug>:<page><letter>" shape, Jowett's public-
# domain 1892 translation, used only to offer the reader a second English
# rendering of a Plato quote alongside the primary (Fowler/Lamb/Bury) text
# already resolved above. This store is optional at the file-system level --
# unlike plato-stephanus.clean.json, whose absence is never tolerated once a
# span names Plato, a missing jowett-stephanus.clean.json simply means "no
# alts available yet" (it is generated by a separate, independent pipeline
# step) and is never fatal.
_JOWETT_CREDIT = "Benjamin Jowett, The Dialogues of Plato, 3rd ed., Oxford, 1892"


def _load_jowett() -> dict[str, str] | None:
    path = SOURCES_DIR / "jowett-plato" / "jowett-stephanus.clean.json"
    if not path.exists():
        return None
    return json.loads(path.read_text(encoding="utf-8"))


# A locus must full-match this shape before any resolver sees it -- an
# inclusive int() conversion (Python tolerates leading '+'/whitespace) would
# otherwise let syntax like "1.+22-040" or "1.22- 40" slip through as if it
# were a well-formed "<book>.<section>"/"<book>.<start>-<end>" locus.
_LOCUS_RE = re.compile(r"^\d+\.\d+(?:-\d+)?$")


def _resolve_diogenes_laertius(locus: str) -> tuple[str, list[str] | None]:
    """`locus` is a Hicks-store key ("1.23") or an inclusive section RANGE
    within one book ("1.22-40") -- the shape a single carried-forward DL
    citation run takes when DK quotes several consecutive Loeb sections
    (see docs/source-passage-english-scoping.md's granularity note). A range
    concatenates each resolved section's Hicks text, in order, separated by
    a blank line (Hicks' own section boundaries read as paragraph breaks);
    any missing section is fatal, not silently skipped. Returns
    `(text, section_loci)`: `section_loci` is the ordered list of resolved
    Hicks keys, one per paragraph in `text`, for a range locus (so the
    reader can mark each paragraph with its own DL section number); `None`
    for a single-section locus (the span's own `locus` already names it)."""
    if not _LOCUS_RE.fullmatch(locus):
        raise ValueError(
            f"Diogenes Laertius locus {locus!r} is not valid -- expected "
            f"'<book>.<section>' or '<book>.<start>-<end>'"
        )
    hicks = _load_hicks()
    if "-" in locus:
        book_s, rng = locus.split(".", 1)
        start_s, end_s = rng.split("-", 1)
        start, end = int(start_s), int(end_s)  # _LOCUS_RE guarantees plain digits
        if end < start:
            raise ValueError(
                f"Diogenes Laertius locus {locus!r}: end section {end} is "
                f"before start section {start}"
            )
        parts = []
        keys = []
        for n in range(start, end + 1):
            key = f"{book_s}.{n}"
            if key not in hicks:
                raise ValueError(
                    f"Diogenes Laertius locus {locus!r} resolves to Hicks "
                    f"section {key!r}, which is not in "
                    f"sources/hicks-dl/hicks-lives.clean.json"
                )
            parts.append(hicks[key])
            keys.append(key)
        return "\n\n".join(parts), keys
    if locus not in hicks:
        raise ValueError(
            f"Diogenes Laertius locus {locus!r} is not a key in "
            f"sources/hicks-dl/hicks-lives.clean.json"
        )
    return hicks[locus], None


# A Plato locus is a single Stephanus "<page><letter>" token ("315c") or an
# inclusive range within one dialogue ("315c-315e") -- never a dialogue name
# (that lives in source_work, resolved by the registry pair below, not
# repeated in the locus) and never an open-ended "ff." (docs/plato-locus-
# resolver-design.md SS3(b): the hand-authoring human pins an explicit end;
# this regex has no way to match an unbounded range, so "ff." simply fails
# to full-match and is rejected like any other malformed locus).
_PLATO_LOCUS_RE = re.compile(r"^\d+[a-e](?:-\d+[a-e])?$")

# Dialogue title, as a context-english.json sidecar names it in source_work
# -> (plato-stephanus.clean.json store slug, translation credit). All 18
# dialogues DK's testimonia/fragments columns cite (docs/plato-locus-
# resolver-design.md SS1's census) -- deliberately not all 36 Platonic
# dialogues; vendoring a 19th later is a one-line table edit plus one file
# copy, per that memo's SS2.4.
_PLATO_DIALOGUES = {
    "Apology": ("apology", "Fowler, 1914"),
    "Charmides": ("charmides", "Lamb, 1927"),
    "Cratylus": ("cratylus", "Fowler, 1926"),
    "Euthydemus": ("euthydemus", "Lamb, 1924"),
    "Gorgias": ("gorgias", "Lamb, 1925"),
    "Hippias Major": ("hippias-major", "Fowler, 1926"),
    "Hippias Minor": ("hippias-minor", "Fowler, 1926"),
    "Laches": ("laches", "Lamb, 1924"),
    "Lysis": ("lysis", "Lamb, 1925"),
    "Meno": ("meno", "Lamb, 1924"),
    "Phaedo": ("phaedo", "Fowler, 1914"),
    "Phaedrus": ("phaedrus", "Fowler, 1914"),
    "Philebus": ("philebus", "Fowler, 1925"),
    "Protagoras": ("protagoras", "Lamb, 1924"),
    "Sophist": ("sophist", "Fowler, 1921"),
    "Symposium": ("symposium", "Lamb, 1925"),
    "Theaetetus": ("theaetetus", "Fowler, 1921"),
    "Timaeus": ("timaeus", "Bury, 1929"),
    # Vendored 2026-07-28 for wired-column candidates (Laws, Republic,
    # Parmenides) and Jowett turn-alignment coverage (Crito, Euthyphro, Ion)
    # -- see sources/perseus-plato/README.md for each dialogue's PD basis.
    "Crito": ("crito", "Fowler, 1914"),
    "Euthyphro": ("euthyphro", "Fowler, 1914"),
    "Ion": ("ion", "Lamb, 1925"),
    "Laws": ("laws", "Bury, 1926"),
    "Parmenides": ("parmenides", "Fowler, 1926"),
    # Republic's store covers the whole dialogue. Perseus's TEI is a 1935-37
    # printing of both Loeb volumes (vol. 1 possibly following Shorey's 1937
    # revision), so NEITHER volume is claimed PD-by-date; the whole text rests
    # on the project owner's explicit pre-1940 ruling, 2026-07-28. See
    # sources/perseus-plato/README.md for the exact wording.
    "Republic": ("republic", "Shorey, 1930-1937 (per owner's pre-1940 ruling, 2026-07-28)"),
}


def _resolve_plato(slug: str):
    """Returns a resolver closure for one dialogue's `slug`, matching
    `_resolve_diogenes_laertius`'s `(text, section_loci)` contract. A range
    expands by INDEX into the store's own key order for this dialogue, never
    by arithmetic on Stephanus numbers (docs/plato-locus-resolver-design.md
    SS5's range-expansion note) -- page letter-counts vary, so "does page
    316 have an 'e'?" is answered by the store, not computed."""

    def resolver(locus: str) -> tuple[str, list[str] | None]:
        if not _PLATO_LOCUS_RE.fullmatch(locus):
            raise ValueError(
                f"Plato locus {locus!r} is not valid -- expected "
                f"'<page><letter>' or '<page><letter>-<page><letter>' "
                f"(an open-ended 'ff.' is never accepted -- a human must "
                f"pin an explicit end)"
            )
        store = _load_plato()
        prefix = f"{slug}:"
        # Document order, not sorted order: preserved from the store JSON's
        # own key order (json.loads keeps insertion order), which IS the
        # dialogue's reading order -- the only order a range may expand by.
        keys = [k[len(prefix):] for k in store if k.startswith(prefix)]
        if "-" in locus:
            start, end = locus.split("-", 1)
            if start not in keys:
                raise ValueError(
                    f"Plato locus {locus!r} resolves to {slug}:{start}, "
                    f"which is not in "
                    f"sources/perseus-plato/plato-stephanus.clean.json"
                )
            if end not in keys:
                raise ValueError(
                    f"Plato locus {locus!r} resolves to {slug}:{end}, "
                    f"which is not in "
                    f"sources/perseus-plato/plato-stephanus.clean.json"
                )
            start_i, end_i = keys.index(start), keys.index(end)
            if end_i < start_i:
                raise ValueError(
                    f"Plato locus {locus!r}: end {end!r} comes before "
                    f"start {start!r} in {slug}'s store order"
                )
            span = keys[start_i : end_i + 1]
            parts = [store[f"{prefix}{k}"] for k in span]
            return "\n\n".join(parts), span
        if locus not in keys:
            raise ValueError(
                f"Plato locus {locus!r} is not a key in "
                f"sources/perseus-plato/plato-stephanus.clean.json for "
                f"{slug!r}"
            )
        return store[f"{prefix}{locus}"], None

    return resolver


# (source_author, source_work) -> resolver, phase 1 (DL) + phase 2 (Plato) --
# docs/source-passage-english-scoping.md's phased plan item 1, and docs/
# plato-locus-resolver-design.md. Registered by the exact PAIR, not by
# author alone: a "translated" span naming an author this module knows but a
# work it doesn't (or a pair it has never seen) is fatal (see
# `_resolve_span`) -- never resolved against the wrong author's store.
# Later phases add their own entries here as their own mechanism work
# lands, never a fallback.
_RESOLVERS = {
    ("Diogenes Laertius", "Lives of Eminent Philosophers"): _resolve_diogenes_laertius,
    **{
        ("Plato", title): _resolve_plato(slug)
        for title, (slug, _credit) in _PLATO_DIALOGUES.items()
    },
}

def _jowett_alts(
    source_author: str, source_work: str, locus: str, section_loci: list[str] | None
) -> dict | None:
    """Builds the `alts` entry for Jowett's translation of a Plato span, or
    `None` when there is nothing to offer -- no Jowett store on disk (not
    generated yet), an unregistered dialogue, or a store with no entry for
    any of this span's loci. `section_loci` is the span's already-resolved
    per-locus list (a range); a single-locus span passes `None` and this
    function falls back to `[locus]` -- the same one-locus-vs-range shape
    `_resolve_span` already carries."""
    if source_author != "Plato":
        return None
    dialogue = _PLATO_DIALOGUES.get(source_work)
    if dialogue is None:
        return None
    slug, _credit = dialogue
    jowett = _load_jowett()
    if jowett is None:
        return None
    loci = section_loci if section_loci else [locus]
    sections = []
    any_hit = False
    for loc in loci:
        key = f"{slug}:{loc}"
        entry: dict = {"locus": loc}
        value = jowett.get(key)
        if isinstance(value, str) and value.strip():
            entry["text"] = value
            any_hit = True
        sections.append(entry)
    if not any_hit:
        return None
    return {
        "id": "jowett",
        "label": "Jowett",
        "translationCredit": _JOWETT_CREDIT,
        "sections": sections,
    }


_REQUIRED_SPAN_FIELDS = ("source_author", "source_work", "locus", "status")


def _validate_emphasis(
    manifest: Manifest, seg_id: str, emphasis: list, text: str
) -> list[str]:
    """Validates a `translated` span's hand-authored `emphasis` list (REVIEW-
    CHECKLIST item 83: source-passage excerpt emphasis) against `text`, the
    already-resolved primary English -- the bold ranges an editor marks as
    the words that actually translate the DK Greek excerpt, distinct from
    the surrounding Stephanus/Hicks context that is not bolded. Each
    substring must occur EXACTLY ONCE in `text` (0 = authoring drift against
    the store, fatal; 2+ = ambiguous anchor, fatal), the substrings must not
    overlap, and they must appear in the same order as `emphasis` declares
    them. Validation runs only against the PRIMARY text -- independent of
    `alts`, which this function never sees."""
    if not isinstance(emphasis, list) or not emphasis:
        raise ValueError(
            f"{manifest.work_id}: context-english.json[{seg_id!r}] emphasis "
            f"must be a non-empty list of strings"
        )
    occurrences = []
    for sub in emphasis:
        if not isinstance(sub, str) or not sub.strip():
            raise ValueError(
                f"{manifest.work_id}: context-english.json[{seg_id!r}] "
                f"emphasis entry {sub!r} must be a non-empty string"
            )
        count = text.count(sub)
        if count == 0:
            raise ValueError(
                f"{manifest.work_id}: context-english.json[{seg_id!r}] "
                f"emphasis substring {sub!r} does not occur in the "
                f"resolved English text -- authoring drift against the store"
            )
        if count > 1:
            raise ValueError(
                f"{manifest.work_id}: context-english.json[{seg_id!r}] "
                f"emphasis substring {sub!r} occurs {count} times in the "
                f"resolved English text -- ambiguous anchor"
            )
        start = text.index(sub)
        occurrences.append((start, start + len(sub), sub))
    by_position = sorted(occurrences, key=lambda t: t[0])
    for (_, end1, sub1), (start2, _, sub2) in zip(by_position, by_position[1:]):
        if start2 < end1:
            raise ValueError(
                f"{manifest.work_id}: context-english.json[{seg_id!r}] "
                f"emphasis substrings {sub1!r} and {sub2!r} overlap"
            )
    if [sub for _, _, sub in by_position] != list(emphasis):
        raise ValueError(
            f"{manifest.work_id}: context-english.json[{seg_id!r}] emphasis "
            f"substrings must be declared in the order they occur in the "
            f"resolved English text"
        )
    return list(emphasis)


def _resolve_span(manifest: Manifest, seg_id: str, span: dict) -> dict:
    missing = [f for f in _REQUIRED_SPAN_FIELDS if not span.get(f)]
    if missing:
        raise ValueError(
            f"{manifest.work_id}: context-english.json[{seg_id!r}] span is "
            f"missing required field(s) {missing}"
        )
    status = span["status"]
    if status not in ("translated", "desert"):
        raise ValueError(
            f"{manifest.work_id}: context-english.json[{seg_id!r}] span has "
            f"status {status!r} -- expected 'translated' or 'desert'"
        )
    # Emitted keys are camelCase (shared/lib/data.ts ContextEnglishSpan),
    # matching the rest of this pipeline's emitted-JSON convention, even
    # though the hand-authored declaration file uses snake_case (matching
    # docs/source-passage-english-scoping.md's Phase C sketch).
    out = {
        "sourceAuthor": span["source_author"],
        "sourceWork": span["source_work"],
        "locus": span["locus"],
        "status": status,
    }
    if status == "desert":
        if span.get("translation_credit"):
            raise ValueError(
                f"{manifest.work_id}: context-english.json[{seg_id!r}] is "
                f"status 'desert' but carries a translation_credit -- a "
                f"desert span has no translation to credit"
            )
        if span.get("emphasis") is not None:
            raise ValueError(
                f"{manifest.work_id}: context-english.json[{seg_id!r}] is "
                f"status 'desert' but declares 'emphasis' -- there is no "
                f"resolved English text to emphasize"
            )
        return out
    # status == "translated"
    credit = span.get("translation_credit")
    if not isinstance(credit, str) or not credit.strip():
        raise ValueError(
            f"{manifest.work_id}: context-english.json[{seg_id!r}] is "
            f"status 'translated' but has no non-empty translation_credit"
        )
    resolver = _RESOLVERS.get((span["source_author"], span["source_work"]))
    if resolver is None:
        raise ValueError(
            f"{manifest.work_id}: context-english.json[{seg_id!r}] names "
            f"source ({span['source_author']!r}, {span['source_work']!r}) "
            f"with status 'translated', but this module has no locus "
            f"resolver registered for that (source_author, source_work) "
            f"pair yet -- add one (or declare the span 'desert' if no PD "
            f"English exists)"
        )
    try:
        text, section_loci = resolver(span["locus"])
    except ValueError as exc:
        raise ValueError(
            f"{manifest.work_id}: context-english.json[{seg_id!r}]: {exc}"
        ) from exc
    out["translationCredit"] = credit
    out["text"] = text
    # Per-paragraph DL section markers (docs/source-passage-english-
    # scoping.md's UX note): only a range locus resolves to more than one
    # paragraph, so only a range locus carries this -- one entry per
    # paragraph in `text`, in order, mirroring the site's own book-section
    # convention (the segment ref shown for a Diogenes Laertius column IS
    # its "book.section" locus string -- see Reader.svelte's `.seg-ref`).
    if section_loci:
        out["sectionLoci"] = section_loci
    if span.get("emphasis") is not None:
        out["emphasis"] = _validate_emphasis(manifest, seg_id, span["emphasis"], text)
    alts = _jowett_alts(span["source_author"], span["source_work"], span["locus"], section_loci)
    if alts:
        out["alts"] = [alts]
    return out


def run(manifest: Manifest, spine: dict) -> Path | None:
    src_path = SOURCES_DIR / manifest.work_id / "context-english.json"
    if not src_path.exists():
        return None
    declared = json.loads(src_path.read_text(encoding="utf-8"))
    if not isinstance(declared, dict):
        raise ValueError(f"{manifest.work_id}: context-english.json must be an object")
    if not declared:
        raise ValueError(
            f"{manifest.work_id}: context-english.json must not be empty -- "
            f"an empty '{{}}' declares no coverage and reads as a truncated "
            f"file, not intentional 'no context English' (delete the file "
            f"instead if the work truly has none)"
        )
    known_ids = {seg["id"] for seg in spine["segments"]}
    unknown = sorted(set(declared) - known_ids)
    if unknown:
        raise ValueError(
            f"{manifest.work_id}: context-english.json names column(s) "
            f"that match no spine segment: {unknown}"
        )
    resolved: dict[str, list[dict]] = {}
    for seg_id, entry in declared.items():
        spans = (entry or {}).get("context_spans")
        if not isinstance(spans, list) or not spans:
            raise ValueError(
                f"{manifest.work_id}: context-english.json[{seg_id!r}] must "
                f"carry a non-empty 'context_spans' list"
            )
        resolved[seg_id] = [_resolve_span(manifest, seg_id, s) for s in spans]
    out_path = BUILD_DIR / "stage1" / "context_english.json"
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(
        json.dumps(resolved, ensure_ascii=False, indent=1), encoding="utf-8"
    )
    return out_path
