"""Deterministic generator for manifests/lives.yaml's
`alignment_allow_unmatched_secondary` list.

Yonge's secondary translation of Diogenes Laertius is keyed at Life level
(one chunk per philosopher, at "<book>.<start_section>" -- see
extract_yonge_dl_gutenberg.py's module docstring for why per-section keying
was measured and rejected), while the Greek spine is keyed per-section
(1,204 columns). Every spine segment that is NOT one of Yonge's 80 Life-start
keys is therefore a genuine, structural secondary-translation gap that
stage1_book_section_english.validate_english_source requires the manifest to
declare explicitly (alignment_allow_unmatched_secondary) or it hard-fails the
build. Hand-typing ~1,124 "book:column" ids would be both tedious and a
silent-drift risk if the spine or Yonge's key set ever changes -- so this
script emits the exact list deterministically from the two real inputs:

    uv run python tools/gen_lives_yonge_allowance.py

Reads:
  - build/stage1/greek_spine.json (produced by `reader_pipeline stage1
    --work lives`; run that first) for the authoritative segment id set.
  - sources/yonge-dl/yonge-lives.clean.json for Yonge's key set.

Prints a YAML list, sorted the same way the spine already orders its
segments (book, then numeric section), ready to paste under
manifests/lives.yaml's `alignment_allow_unmatched_secondary:` -- the
manifest's own comment there names this script so a future re-run reproduces
the same list from the same two inputs.
"""
from __future__ import annotations

import json
from pathlib import Path

PIPELINE_DIR = Path(__file__).resolve().parents[1]
REPO_DIR = PIPELINE_DIR.parent
SPINE_PATH = REPO_DIR / "build" / "stage1" / "greek_spine.json"
YONGE_PATH = REPO_DIR / "sources" / "yonge-dl" / "yonge-lives.clean.json"


EXPECTED_WORK_ID = "lives"
EXPECTED_SEGMENT_COUNT = 1204  # lives.yaml's section_spine.count — see its comment


def main() -> None:
    spine = json.loads(SPINE_PATH.read_text(encoding="utf-8"))
    yonge_keys = set(json.loads(YONGE_PATH.read_text(encoding="utf-8")))

    # Sol Minor 1 (review round, 2026-07-16): this script used to trust
    # build/stage1/greek_spine.json blindly — if it's stale (built for a
    # different --work, or a pre-fix spine before a stage1 bugfix) the
    # generated allowance list silently encodes the wrong spine. Fail loudly
    # instead.
    if spine.get("work") != EXPECTED_WORK_ID:
        raise SystemExit(
            f"{SPINE_PATH} is work {spine.get('work')!r}, not "
            f"{EXPECTED_WORK_ID!r} — re-run `reader_pipeline stage1 --work "
            f"lives` first"
        )

    segments = spine["segments"]
    if len(segments) != EXPECTED_SEGMENT_COUNT:
        raise SystemExit(
            f"{SPINE_PATH} has {len(segments)} segments, expected "
            f"{EXPECTED_SEGMENT_COUNT} (manifests/lives.yaml's "
            f"section_spine.count) — the spine looks stale or the Greek "
            f"export/parse has changed; re-run `reader_pipeline stage1 "
            f"--work lives` and, if the count is genuinely different now, "
            f"update this script's EXPECTED_SEGMENT_COUNT and lives.yaml's "
            f"section_spine together"
        )

    missing = [
        seg["id"] for seg in segments if seg["column"] not in yonge_keys
    ]

    covered = len(segments) - len(missing)
    print(f"# generated by pipeline/tools/gen_lives_yonge_allowance.py")
    print(f"# spine segments: {len(segments)}, Yonge keys: {len(yonge_keys)}, "
          f"covered: {covered}, allowed-gap: {len(missing)}")
    for seg_id in missing:
        print(f'  - "{seg_id}"')


if __name__ == "__main__":
    main()
