"""Turn a gloss-aligner map into a hand-keyed-style anchors.yaml.

The gloss aligner emits `alignment-results/<vid>/<WORK>_<vid>_gloss_map.json`
({"book:chapter": {ross_len, anchors:[{citation, offset, tier, confidence}]}}).
For a primary archive translation the reader gets its real Bekker gutter from
`sources/<dir>/anchors.yaml` (a list of {bekker, at} — `at` is a verbatim phrase
in the translation at that Bekker line), NOT from the gloss map: `build_english`
in stage1_archive only reads anchors.yaml. This script converts one into the
other so a gloss-aligned primary (APr/Jenkinson, Cat/Edghill, Pol/Jowett) can be
wired into the public build.

Each real cadence tick (tier chapter/column/five_line — the interpolated `line`
ticks are dropped; the reader re-interpolates between cadence ticks) becomes one
{bekker, at} entry, where `at` is the verbatim prose starting at the tick offset.
The phrase is located by `_resolve_anchors` within its Bekker column's chunk, so
a short window suffices.

Usage (from pipeline/):
    uv run python tools/gloss_map_to_anchors.py <WORK> <vid>
e.g. `... APr jenkinson` → writes sources/apr-jenkinson/anchors.yaml.
"""
import json
import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from reader_pipeline.config import SOURCES_DIR, Manifest
from reader_pipeline.stage1_ross import parse_translation

# Cadence tiers carry real, verifier-grade placements; `line` ticks are the
# pass-1 interpolation between them and are regenerated by the reader. The
# `column` tier (Bekker line 1 of a column) is omitted: add_bekker_gutter already
# pins every column's first line as a real tick at offset 0 structurally, and a
# column-start phrase straddles the proportional column cut (its opening words
# fall in the previous column's chunk), so it would never resolve anyway.
REAL_TIERS = {"chapter", "five_line"}
PHRASE_CHARS = 80   # window length before trimming to a word boundary


def _phrase(text: str, offset: int) -> str:
    """A verbatim phrase of `text` starting at `offset`, whitespace-collapsed and
    trimmed to a trailing word boundary so an exact substring search finds it."""
    window = " ".join(text[offset:offset + PHRASE_CHARS].split())
    if len(window) == PHRASE_CHARS and " " in window:
        window = window[: window.rfind(" ")]   # drop a clipped trailing word
    return window.strip()


def _column_key(citation: str) -> tuple:
    """Sort key: (page, a-before-b, line) so 52b38 follows 52a* and precedes 53a1."""
    m = re.match(r"^(\d+)([ab])(\d+)$", citation)
    if not m:
        return (0, "", 0)
    return (int(m.group(1)), m.group(2), int(m.group(3)))


def build(work_id: str, vid: str) -> list[dict]:
    eng = Manifest.for_work(work_id).data["english"]
    prim = eng.get("primary") or eng.get("secondary")
    marker = prim.get("chapter_marker", prim.get("marker", "number"))
    prose = parse_translation(SOURCES_DIR / prim["dir"], prim["books"], marker)

    map_path = (SOURCES_DIR.parent / "alignment-results" / vid
                / f"{work_id}_{vid}_gloss_map.json")
    gmap = json.loads(map_path.read_text(encoding="utf-8"))

    seen: set[str] = set()
    entries: list[dict] = []
    for key, entry in gmap.items():
        book, chap = (int(x) for x in key.split(":"))
        text = prose.get((book, chap), "")
        drift = len(text) - entry.get("ross_len", -1)
        # A few chars of *trailing* whitespace drift (e.g. the source/parser
        # gaining a trailing newline per chapter after the map was built) does not
        # move any anchor offset, so the extracted phrases are unchanged. Tolerate
        # a small drift with a warning; abort only on a large mismatch that would
        # actually desync offsets (wrong dir/marker, real re-chunking).
        if drift != 0:
            if abs(drift) > 4:
                raise SystemExit(
                    f"prose length mismatch for {key}: {len(text)} != {entry['ross_len']} "
                    "(rebuild stage1 / check the manifest dir & marker)")
            print(f"warn: {key} prose length drift {drift:+d} (trailing; tolerated)",
                  file=sys.stderr)
        for a in entry["anchors"]:
            if a["tier"] not in REAL_TIERS:
                continue
            cit = a["citation"]
            if cit in seen:
                continue
            phrase = _phrase(text, a["offset"])
            if not phrase:
                continue
            seen.add(cit)
            entries.append({"bekker": cit, "at": phrase})
    entries.sort(key=lambda e: _column_key(e["bekker"]))
    return entries


def main() -> None:
    if len(sys.argv) != 3:
        raise SystemExit("usage: gloss_map_to_anchors.py <WORK> <vid>")
    work_id, vid = sys.argv[1], sys.argv[2]
    entries = build(work_id, vid)
    prim = Manifest.for_work(work_id).data["english"]
    prim = prim.get("primary") or prim.get("secondary")
    out = SOURCES_DIR / prim["dir"] / "anchors.yaml"
    # JSON double-quoted scalars are valid YAML and escape quotes/colons safely.
    lines = [f'- bekker: "{e["bekker"]}"\n  at: {json.dumps(e["at"], ensure_ascii=False)}'
             for e in entries]
    out.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"wrote {len(entries)} anchors → {out.relative_to(SOURCES_DIR.parent)}")


if __name__ == "__main__":
    main()
